[
  { word: "Accommodation", translation: "turar joy", emoji: "🏠" },
  { word: "Waste", translation: "chiqindi, isrof", emoji: "🚮" },
  { word: "Coast", translation: "sohil", emoji: "🌊" },
  { word: "Rainforest", translation: "yomg‘ir o‘rmoni", emoji: "🌳🌧️" },
  { word: "Caravan", translation: "karvon, avtouy", emoji: "🚐" },
  { word: "Chalet", translation: "yozgi uy", emoji: "🏡" },
  { word: "Ride", translation: "minish", emoji: "🎢" },
  {
    word: "BBQ (Barbecue)",
    translation: "barbekyu, kabob pishirish",
    emoji: "🍖🔥",
  },
  { word: "Mostly", translation: "asosan", emoji: "📊" },
  { word: "All-inclusive", translation: "hammasi kiritilgan", emoji: "🎟️🛏️🍽️" },
  { word: "Barbados", translation: "Barbados (orol)", emoji: "🏝️" },
  { word: "City break", translation: "shaharga qisqa safar", emoji: "🏙️✈️" },
  { word: "History", translation: "tarix", emoji: "📜🏛️" },
  { word: "Geography", translation: "geografiya", emoji: "🌍🗺️" },
  { word: "Iceland", translation: "Islandiya", emoji: "🇮🇸❄️" },
  { word: "Volcano", translation: "vulqon", emoji: "🌋" },
  { word: "Waterfall", translation: "sharshara", emoji: "🌊⛲" },
  { word: "Glacier", translation: "muzlik", emoji: "🧊🏔️" },
  { word: "Awesome", translation: "ajoyib", emoji: "🤩" },
  {
    word: "Experience",
    translation: "tajriba, boshdan kechirish",
    emoji: "🎭",
  },
  {
    word: "It doesn't matter",
    translation: "farqi yo‘q, ahamiyati yo‘q",
    emoji: "🤷",
  },
  { word: "Hot spring", translation: "issiq buloq", emoji: "♨️" },
  { word: "Lagoon", translation: "laguna", emoji: "🌊🏝️" },
  {
    word: "The Northern Lights",
    translation: "Shimoliy yog‘du (aurora)",
    emoji: "🌌",
  },
  { word: "Erupt", translation: "otilmoq (vulqon)", emoji: "🌋💥" },
  { word: "Explode", translation: "portlamoq", emoji: "💣💥" },
  { word: "Ash", translation: "kul", emoji: "⚱️" },
  { word: "Powder", translation: "kukun", emoji: "💨" },
  { word: "Sunset", translation: "quyosh botishi", emoji: "🌇" },
  { word: "Hole", translation: "teshik", emoji: "🕳️" },
  { word: "Cliff", translation: "qoya", emoji: "⛰️" },
  { word: "Cover", translation: "qoplamoq, yopmoq", emoji: "🛡️" },
  { word: "Root", translation: "ildiz", emoji: "🌱" },
  { word: "Pretty", translation: "chiroyli, anchagina", emoji: "😊" },
  {
    word: "Sunglasses",
    translation: "quyoshdan saqlovchi ko‘zoynak",
    emoji: "🕶️",
  },
  { word: "Seaside", translation: "dengiz bo‘yi", emoji: "🏖️" },
  { word: "Uncommon", translation: "kam uchraydigan", emoji: "🔍" },
  { word: "Average", translation: "o‘rtacha", emoji: "📉" },
  { word: "Odd", translation: "g‘alati", emoji: "🤔" },
  { word: "Unnatural", translation: "tabiiy bo‘lmagan", emoji: "🧪" },
  { word: "Blog Entry", translation: "blog yozuvi", emoji: "📝" },
  { word: "Continent", translation: "qit'a", emoji: "🌍" },
  { word: "Asia", translation: "Osiyo", emoji: "🇨🇳" },
  { word: "Africa", translation: "Afrika", emoji: "🇿🇦" },
  { word: "Oceania", translation: "Okeaniya", emoji: "🇦🇺" },
  { word: "North America", translation: "Shimoliy Amerika", emoji: "🇺🇸" },
  { word: "South America", translation: "Janubiy Amerika", emoji: "🇧🇷" },
  { word: "Population", translation: "aholi", emoji: "👥" },
  { word: "Million", translation: "million", emoji: "1️⃣0️⃣0️⃣0️⃣0️⃣0️⃣0️⃣" },
  { word: "Safari Park", translation: "safari parki", emoji: "🦁🌿" },
  { english: "Inca", translation: "Inka 🏛️" },
  { english: "Landscape", translation: "manzara 🏞️" },
  { english: "South Korea", translation: "Janubiy Koreya 🇰🇷" },
  { english: "High tech", translation: "yuqori texnologiya 🖥️" },
  { english: "Bed and breakfast", translation: "tunash va nonushta 🏨🍽️" },
  { english: "Caravan park", translation: "avtouylar parki 🚐🏕️" },
  { english: "Basic", translation: "asosiy, oddiy 🔤" },
  { english: "Cheap", translation: "arzon 💰" },
  { english: "Park", translation: "park 🌳" },
  { english: "Toast", translation: "qovurilgan non 🍞" },
  { english: "Uncomfortable", translation: "noqulay 😣" },
  {
    english: "Tourist information centre",
    translation: "sayyohlar uchun ma'lumot markazi 🏝️📍",
  },
  { english: "Travel agent", translation: "sayohat agenti 🧳🗺️" },
  { english: "Holiday resort", translation: "dam olish maskani 🏖️" },
  { english: "Sight", translation: "diqqatga sazovor joy 👀" },
  { english: "Map", translation: "xarita 🗺️" },
  { english: "Amusement park", translation: "ko‘ngilochar park 🎡🎢" },
  { english: "Day trip", translation: "bir kunlik sayohat 🚗" },
  { english: "Excursion", translation: "ekskursiya 🚶‍♂️" },
  { english: "Suitcase", translation: "chamadon 🧳" },
  { english: "Wander", translation: "sayr qilish 🚶" },
  { english: "Wonder", translation: "ajablanmoq, hayrat 🤩" },
  { english: "Earth", translation: "Yer (sayyora) 🌍" },
  { english: "Colosseum", translation: "Kolizey 🏛️" },
  { english: "Postcard", translation: "ochiqcha (xat) 📨" },
  { english: "Giant tortoise", translation: "ulkan toshbaqa 🐢" },
  { english: "Galapagos Islands", translation: "Galapagos orollari 🏝️" },
  { english: "Dubai", translation: "Dubay 🇦🇪" },
  { english: "Taxi driver", translation: "taksi haydovchisi 🚖" },
  { english: "Tram", translation: "tramvay 🚋" },
  { english: "Sweetly", translation: "yoqimli tarzda 😊" },
  { english: "Politely", translation: "odob bilan 🙏" },
  { english: "Angrily", translation: "g‘azab bilan 😡" },
  { english: "Hungrily", translation: "ochko‘zlik bilan 🍽️" },
  { english: "Miss", translation: "sog‘inmoq, o‘tkazib yubormoq 😢" },
  { english: "Take place", translation: "sodir bo‘lmoq 📆" },
  { english: "Empty", translation: "bo‘sh ⚪" },
  { english: "Hometown", translation: "tug‘ilgan shahar 🏠" },
  { english: "Social media", translation: "ijtimoiy tarmoq 📱" },
  { english: "Post", translation: "post, xabar joylamoq 📝" },
  { english: "Flow", translation: "oqim, oqmoq 🌊" },
  { english: "Smoothly", translation: "muammosiz, silliq tarzda ✅" },
  { english: "Avoid", translation: "qochmoq, oldini olmoq 🚫" },
  { english: "Enjoyable", translation: "maroqli 😃" },
  { english: "Later", translation: "keyinroq ⏳" },
  { english: "Bye", translation: "xayr 👋" },
  { english: "Vintage", translation: "qadimiy, klassik 🏺" },
  { english: "Contraction", translation: "qisqarish 🔽" },
  { english: "Full stop", translation: "nuqta 🔴" },
  { english: "Question mark", translation: "so'roq belgisi (?) ❓" },
  { english: "Fall in love", translation: "sevib qolmoq ❤️" },
  { english: "Newspaper", translation: "gazeta 📰" },
  { english: "Religion", translation: "din 🛐" },
  { english: "Snake charmer", translation: "ilon o‘ynatuvchi 🐍🎶" },
  { english: "Fortune teller", translation: "folbin 🔮" },
];
